services:
  postgres:
    image: "postgres:17-alpine"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=$DATABASE_USERNAME
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - POSTGRES_DB=$DATABASE_NAME
    ports:
      - "$DATABASE_PORT:5432"
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
